name: p_value_ri
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.24.1
  - scikit-learn=1.2.0
  - scipy=1.10.0
  - cython=0.29.33
  - mpmath=1.2.1
  - pandas=1.5.3
  - pyamg=5.0.1
  - tqdm=4.65.0
  - networkit=10.1
  - networkx=3.1
  - tabulate=0.9.0
